// Autogenerated from Pigeon (v1.0.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, MessageKey) {
  MessageKeyTitle = 0,
  MessageKeySubtitle = 1,
  MessageKeyDescription = 2,
};

@class Message;

@interface Message : NSObject
@property(nonatomic, strong, nullable) NSNumber * id;
@property(nonatomic, strong, nullable) NSDictionary<MessageKey *, NSString *> * additionalProperties;
@end

/// The codec used by HostApiBridge.
NSObject<FlutterMessageCodec> *HostApiBridgeGetCodec(void);

@protocol HostApiBridge
- (void)sendMessageMessage:(Message *)message error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void HostApiBridgeSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HostApiBridge> *_Nullable api);

NS_ASSUME_NONNULL_END
