// Autogenerated from Pigeon (v1.0.10), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "HostApi.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}

@interface Message ()
+ (Message *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation Message
+ (Message *)fromMap:(NSDictionary *)dict {
  Message *result = [[Message alloc] init];
  result.id = dict[@"id"];
  if ((NSNull *)result.id == [NSNull null]) {
    result.id = nil;
  }
  result.additionalProperties = dict[@"additionalProperties"];
  if ((NSNull *)result.additionalProperties == [NSNull null]) {
    result.additionalProperties = nil;
  }
  return result;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.id ? self.id : [NSNull null]), @"id", (self.additionalProperties ? self.additionalProperties : [NSNull null]), @"additionalProperties", nil];
}
@end

@interface HostApiBridgeCodecReader : FlutterStandardReader
@end
@implementation HostApiBridgeCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [Message fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface HostApiBridgeCodecWriter : FlutterStandardWriter
@end
@implementation HostApiBridgeCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[Message class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface HostApiBridgeCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation HostApiBridgeCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[HostApiBridgeCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[HostApiBridgeCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *HostApiBridgeGetCodec() {
  static dispatch_once_t s_pred = 0;
  static FlutterStandardMessageCodec *s_sharedObject = nil;
  dispatch_once(&s_pred, ^{
    HostApiBridgeCodecReaderWriter *readerWriter = [[HostApiBridgeCodecReaderWriter alloc] init];
    s_sharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return s_sharedObject;
}


void HostApiBridgeSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<HostApiBridge> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.HostApiBridge.sendMessage"
        binaryMessenger:binaryMessenger
        codec:HostApiBridgeGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendMessageMessage:error:)], @"HostApiBridge api (%@) doesn't respond to @selector(sendMessageMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        Message *arg_message = args[0];
        FlutterError *error;
        [api sendMessageMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
